nome = str(input('Digite seu nome completo: ')).strip().lower()
contador = nome.count(' ')
nome1 = nome.split()
print('Muito prazer em te conhecer!')
print(f'Seu primeiro nome é {nome1[0].capitalize()}')
print(f'Seu último nome é {nome1[contador].capitalize()}')
